name: Export and Deploy Web Preview

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Godot 4 (headless) with export templates
        uses: nhartland/setup-godot@v1
        with:
          version: '4.5'
          use-mono: false
          export-templates: true

      - name: Export Web (HTML5)
        run: |
          mkdir -p build/web
          godot --headless --path . --export-release "Web" build/web/index.html

      - name: Upload web artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: export-web
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
